services:
  kestra:
    image: kestra/kestra:v1.3.1
    pull_policy: always#
    user: "root"
    command: server standalone --flow-path /flows
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./../keys:/keys:ro               # mounts keys/ folder as read-only
      - ./../kestra/flows:/flows
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/keys/gcp-creds.json'
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /flows
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: Admin1234
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: /app/storage
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd
          url: http://localhost:8080/
          tutorial-flows:
            enabled: false
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local
